phil-inc/phil-us-contentful

src/components/common/Carousel/TestimonialCarousel.tsx, src/components/common/Testimonial.tsx, src/components/section/ReferencedSection.tsx, yarn.lock
=> [REVIEW] Testimonial caraousel

src/components/Blog/BlogSection.tsx, src/components/FAQSection/FAQSection.tsx, src/components/common/Asset/Asset.tsx, src/components/common/FAQ.tsx, src/components/section/ReferencedSection.tsx, src/hooks/useInternalPaths.ts, src/layouts/Layout/CFooter/CFooter.tsx, src/templates/blog.tsx, src/utils/getLink.ts
=> [STYLE]: Style updates

src/components/common/HubspotFormModal.tsx, src/components/section/BasicSection.tsx, src/layouts/Layout/CFooter/CFooter.tsx, src/layouts/Layout/CHeader/CHeader.tsx, src/templates/page.tsx
This PR adds static pages from contentful.
=> [FIX]: Terms + Privacy +  Hippa pages

src/assets/css/hubspot-form.css, src/assets/css/mantine-accordion-override.css, src/components/common/Article.tsx, src/components/common/Asset/Asset.tsx, src/components/common/Banner/Banner.tsx, src/components/common/Container/ImageContainer.tsx, src/components/section/BasicSection.tsx, src/components/section/Section.tsx, src/layouts/Layout/CFooter/CFooter.tsx, src/layouts/Layout/Layout.tsx, src/templates/career.tsx
This PR includes style updates for home page, footer, video assets.
=> [STYLE]: Style updates 

src/components/common/Featured.tsx, src/components/common/Resources/ResourceCard.tsx, src/components/section/ReferencedSection.tsx, src/layouts/Layout/CFooter/CFooter.tsx, src/layouts/Layout/CHeader/CHeader.tsx, src/layouts/Layout/Layout.tsx
This PR contains responsive fixes and UX updates.
- Updated navbar toggle logic.
- Updated responsive layout on Featured Resources, FAQs, footer badges and resource cards.
=> [STYLE]: UI/UX updates

gatsby-config.js
This PR adds the google ads page view event.
=> [ANALYTICS]: Add google ads page view event

package.json, src/components/common/Article.tsx, src/components/common/Banner/Banner.tsx, src/components/common/Carousel/ResourceCarousel.tsx, src/components/common/Container/ImageContainer.tsx, src/components/common/Expanded/Expanded.tsx, src/components/common/Featured.tsx, src/components/common/prescriberJourney/PrescriberJourney.tsx, src/components/common/statsCard/StatsCard.tsx, src/components/section/BasicSection.tsx, src/components/section/ReferencedSection.tsx, src/layouts/Layout/CFooter/CFooter.tsx, src/layouts/Layout/CHeader/CHeader.tsx, src/layouts/Layout/Layout.tsx, src/templates/career.tsx, src/utils/groupBy.ts
=> [STYLE]: Update style to meet design verification 

src/layouts/Layout/Layout.tsx
This PR updates metadata pixel script.
=> [ANALYTICS]: Metadata pixel updated

src/components/common/FAQ.tsx, src/layouts/Layout/CFooter/CFooter.tsx, src/layouts/Layout/Layout.tsx, src/templates/blog.tsx
This PR includes updates for design verification and QA feedback minor changes.
=> [QA/DV]: QA/Design verification feedback changes 

src/components/section/BasicSection.tsx
This PR updates the list item font color.
=> [STYLE]: update font color for list item

src/layouts/Layout/CFooter/CFooter.tsx, src/templates/page.tsx
This PR includes updates for formComplete code snippet in the head of contact page.
=> [ANALYTICS]: Add formComplete snippet code

src/components/common/Container/ImageContainer.tsx, src/components/common/Expanded/Expanded.tsx, src/components/section/ReferencedSection.tsx, src/layouts/Layout/CHeader/CHeader.tsx
This PR includes updates to fix bugs introduced by contentful environment migration.
=> [STYLE]: fix migration bugs

src/templates/career.tsx
This PR includes updates for hotfix for career page incorrect link.
=> [HOTFIX]: hotfix career page

src/utils/groupBy.ts
This PR includes updates for hotfixing career job title mapping.
=> [HOTFIX]: hotfix career page mapping

gatsby-node.js, src/components/common/Carousel/ResourceCarousel.tsx, src/types/asset.ts
This PR includes updates for adding ids to graphql.
=> [FIX]: add ids to graphql query

src/templates/blog.tsx
This PR fixes the bug for blog links not clicking.
=> [HOTFIX]: hotfix blog links not working

src/layouts/Layout/Layout.tsx, src/templates/blog.tsx
This PR incldues updates for styling on blog pages.
=> [STYLE]: update styling on blog pages

src/layouts/Layout/Layout.tsx, src/templates/page.tsx
This PR includes updates to fix the metadata pixel firing twice.
=> [BUG]: update pixel firing location

src/layouts/SEO/SEO.tsx, src/templates/page.tsx
This PR includes updates to include the metadata pixel to be fired globally.
=> [BUG]: update pixel firing location to be globally available

package.json, src/layouts/Layout/CHeader/CHeader.tsx, src/templates/blog.tsx, yarn.lock
This PR includes updates for minor bug fixes.
- Add scroll transition/animation to navigaret to sections on same page from header on mobile
- Add line break to paragraphs by using p component instead of Text
=> [BUG]: Bug Fix 

src/assets/css/hubspot-form.css, src/layouts/Layout/CFooter/CFooter.tsx, src/layouts/Layout/CHeader/CHeader.tsx
This PR includes updates for minor bug fixes.
- Add LinkedIn icon in footer on mobile
- Hide error rollup message on hubspot forms
=> [BUG]: Bug Fixes 

gatsby-node.js, src/templates/blog.tsx, src/types/resource.ts
This PR includes updates to add banners to blog pages.
- Use Dummy Resource to get default banner 
- Add banner resource to blog template
=> [FEATURE]: Add banners to blog pages

gatsby-node.js, src/layouts/Layout/CFooter/CFooter.tsx, src/layouts/Layout/CHeader/CHeader.tsx, src/templates/career.tsx, src/templates/page.tsx, src/types/page.ts, src/utils/getTitle.ts
This PR includes updates to add ability to change page titles without causing build errors and slug mismatch.
=> [FEATURE]: change page title which doesnot affect slugs

README.md, gatsby-config.js, package.json, yarn.lock
This PR includes updates for adding robots.txt
- add robots.txt plugin
- update readme
=> [SEO]: add robots.txt

src/utils/getDescription.ts
This PR includes hotfix updates for lookbehind not supported in safari browser.
=> [HOTFIX] - lookbehind not supported by safari

src/templates/blog.tsx
Fix embeded assets overlapping
=> [HOTFIX] - make embeded assets not float

src/layouts/Layout/CHeader/CHeader.tsx
This PR fixes a bug for header section which was using static span
=> [BUG]: Fix header sections

src/components/common/Buttons/SocialButtons/SocialButton.tsx
=> [SYNC]: Sync repo

src/analytics/LinkedinInsights.tsx, src/analytics/ZoominfoAnalytics.tsx, src/layouts/Layout/Layout.tsx
This PR updates scripts for broken js.
=> [ANALYTICS]: update scripts

gatsby-node.js, netlify.toml, src/components/Blog/BlogSection.tsx, src/components/FAQSection/FAQSection.tsx, src/components/common/Resources/ResourceCard.tsx, src/templates/blog.tsx, src/types/resource.ts
This PRincludes updates to add short headings (subheading) to the blog pages and resource cards.
- Add subheading field in contentful for short headings (subheading)
- Rename api field for meta description
- Rename api field for subheading
=> [FEATURE]: Short heading blogs

netlify.toml
Move /manufacturer route with 301
=> [HOTFIX]: 301 move /manufacturer

netlify.toml
This PR fixes seo audit duplicate content issues.
=> [HOTFIX]: fix duplicate content with redirects

netlify.toml
Reverts phil-inc/phil-us-contentful#112
=> Revert "[HOTFIX]: fix duplicate content with redirects"

src/layouts/Layout/CHeader/CHeader.tsx
This PR fixes some mobile browers cutting off patient login button.
=> [HOTFIX]: fix button cutoff in mobile

src/components/section/BasicSection.tsx
This PR fixes a bug where the check for contact page is changed due to adding of trailing slashes for SEO.
=> [HOTFIX]: hotfix contact page, add slashes

gatsby-node.js, src/components/common/Asset/Asset.tsx, src/components/section/BasicSection.tsx, src/types/section.ts
This PR fixes the origin issue printed in console when embeding youtube videos.
[Asana link](https://app.asana.com/0/0/1203968964537126/f)
=> [BUG]: youtube embed origin error 

src/components/common/Buttons/SocialButtons/SocialButton.tsx, src/utils/socialShare.ts
Update the links with override for social share
=> [BUG]: update social share links

src/components/common/Asset/Asset.tsx, src/components/section/BasicSection.tsx
This PR includes updates to solve some minor bugs.
- Add origin of https://www.youtube.com for origin in embeded video
- Add scroll to top feature for hubspot forms submit buttons
https://www.loom.com/share/a0310abab43141c09cb36ffea67f19cf
=> [BUG]: Minor fixes

gatsby-config.js, gatsby-node.js, src/components/career/CareerArticle.tsx, src/components/career/CareerSection.tsx, src/components/common/Buttons/SocialButtons/SocialButton.tsx, src/templates/blog.tsx, src/templates/page.tsx, src/types/resource.ts
This PR adds support for noindex tags for required pages.
- Add noindex field in contentful
- Add `/field` paths to be ignored in sitemap
- Update careers page styling
- Bug fix share link sometimes not populating
https://www.loom.com/share/20e1d6e6cf7e4dbd86aa8d1a3197fa10
=> [FEATURE]: noindex tag + minor fixes

src/components/common/Buttons/SocialButtons/SocialButton.tsx, src/utils/socialShare.ts
This PR fixes the social share links that are sometimes broken due to SSG.
- the links are there now
=> [HOTFIX]: hotfix share links

src/components/common/Buttons/SocialButtons/SocialButton.tsx, src/templates/blog.tsx, src/utils/socialShare.ts
This PR includes updates to hide social share buttons in noindex pages.
https://www.loom.com/share/1e2f98e4e34e4a2989d6fa29afd2a3d0
=> [FEATURE]: Hide social share and banner in noindex pages

gatsby-node.js, package.json, src/components/ContactPageForm/ContactForm.tsx, src/components/section/BasicSection.tsx, src/contexts/ContactFormContext.tsx, src/layouts/Layout/Layout.tsx, src/templates/contact.tsx, src/utils/http.ts, yarn.lock
This PR changes design for the new `/field` path
https://www.loom.com/share/8ff0ed0b3b1d4a46bb85983f1ab4efb1
https://www.loom.com/share/2023352612014c919b544570eb45c142
=> [FEATURE]: Add accordian items to /field page 

src/components/common/Expanded/Expanded.tsx, src/components/common/FAQ.tsx, src/components/section/ReferencedSection.tsx, src/contexts/PageContext.tsx, src/templates/page.tsx
This PR changes design for the new `/field` path
https://www.loom.com/share/8ff0ed0b3b1d4a46bb85983f1ab4efb1
https://www.loom.com/share/2023352612014c919b544570eb45c142
=> [FEATURE]: Add accordian items to /field page

src/components/common/Expanded/Expanded.tsx, src/components/common/FAQ.tsx, src/components/section/ReferencedSection.tsx, src/contexts/PageContext.tsx, src/templates/page.tsx
Reverts phil-inc/phil-us-contentful#143
=> Revert "v1.7.1"

src/components/section/ReferencedSection.tsx
This PR updates the mobile layout for /field page
=> [FEATURE]: Update /field for mobile layout

src/components/section/ReferencedSection.tsx
This PR hotfixes the font size.
=> [HOTFIX]: Update font size

src/assets/css/hubspot-form.css, src/components/common/Expanded/Expanded.tsx, src/components/section/ReferencedSection.tsx, src/templates/page.tsx
This PR includes updates for spacing fixes on mobile.
- Add spacing fixes
=> [FEATURE]: update mobile spacing for field

src/components/section/ReferencedSection.tsx
This Pr adjusts the padding in investors section for mobile and desktop.
=> [BUG]: update padding in investors section

src/components/ContactPageForm/ContactForm.tsx
This PR updates the button styling on contact us page
=> [DESIGN]: update button on contact page

src/components/common/Container/ImageContainer.tsx
This PPR fixes the image overlapping in contact page
- contain image in section
=> [BUG]: update image height to contain image in section

src/components/ContactPageForm/ContactForm.tsx, src/components/common/Container/ImageContainer.tsx, src/components/common/FAQ.tsx, src/components/common/HubspotFormModal.tsx, src/components/section/BasicSection.tsx, src/components/section/Section.tsx, src/constants/page.ts, src/layouts/Layout/CFooter/CFooter.tsx, src/templates/contact.tsx
This PR fixes the image overlap bug on contact page.
=> [BUG]: Fix image overlap

netlify.toml
redirect https://phil.us/md/enroll  to https://forms.gle/rNbj6LQ4po1pmcpr6
=> create redirection for md/enroll

src/api/channel-comparision/[id].ts, src/constants/api.ts
This PR updates the base uri for channel-comparision gatsby function.
=> update api function base uri

src/components/ChannelComparision/EmailCollection.tsx, src/components/ChannelComparision/Information.tsx
This PR includes UI updates to remove spacing in required '*' and make '*' not wrap in email collection.
=> [STYLE]: Update styling

src/components/ChannelComparision/Information.tsx, src/contexts/ChannelComparisionContext.tsx, src/pages/channel-comparision.tsx
This PR adds a hidden field for channel comparision and hutk from cookies to track leads to contacts.
=> [FEATURE]: Add hidden field and hutk

src/constants/page.ts, src/layouts/Layout/CFooter/CFooter.tsx, src/layouts/Layout/CHeader/CHeader.tsx, src/utils/getFinalIndex.ts
This PR adds HCP login buttons.
=> [FEATURE]: update HCP login

src/components/common/Asset/Asset.tsx, src/components/common/Container/ImageContainer.tsx, src/components/section/BasicSection.tsx, src/templates/blog.tsx
This PR includes updates for video assets styling all over the website.
- seperate youtube and normal video embeds
=> [FEATURE]: Update video assets styling

src/components/ChannelComparision/Information.tsx, src/contexts/ChannelComparisionContext.tsx, src/pages/channel-comparision.tsx
This PR adds a drug_name hidden field that has a unique value.
=> [FEATURE]: drug_name added

netlify.toml
Redirect /md/enroll and /hcp/enroll to https://md.phil.us/enroll
=> hcp enroll redirection

netlify/edge-functions/getCareerListing.ts
use the location from the api, instead of composing.
=> ashby location fix

src/components/common/Resources/ResourceCard.tsx, src/utils/getLink.ts
https://phildotus.atlassian.net/browse/MRTG-1122
=> MRTG: Add a style for external link and fix the redirect issue problem

src/templates/executive-team.tsx, src/templates/executiveTeam.module.css
> Changes Made
- Adjust padding of the cards and gap between the columns
- Change the title of the page
=> Et page design fixes

src/layouts/Layout/CFooter/DesktopFooter.tsx, src/layouts/Layout/CFooter/MobileFooter.tsx
Move Executive team to top in company section in footer
=> Move Executive team to top in company section

src/layouts/Layout/CFooter/DesktopFooter.tsx, src/layouts/Layout/CFooter/MobileFooter.tsx
Fix spacing of link in company section in Footer in mobile view
Before screenshot:
After screenshot:
=> Fix spacing in mobile view

src/components/CommitmentCard/CommitmentCard.tsx, src/components/CommitmentCard/commitmentCard.module.css, src/components/FeaturedInsights/FeaturedInsights.tsx, src/components/FeaturedInsights/featuredInsights.module.css, src/components/brandOutcomeCard/BrandOutcomeCard.tsx, src/components/brandOutcomeCard/brandOutcomeCard.module.css, src/components/common/Card/CardSection/CardSection.tsx, src/components/common/Card/CardSection/cardSection.module.css, src/components/common/Expanded/expanded.module.css, src/components/section/ReferencedSection/ReferencedSection.tsx, src/components/section/ReferencedSection/ReferencedSectionBody.tsx, src/components/section/ReferencedSection/ReferencedSectionTitle.tsx, src/components/section/ReferencedSection/RenderResource.tsx, src/components/section/ReferencedSection/referencedSection.module.css, src/components/section/ReferencedSection/referencedSectionTitle.module.css, src/layouts/Layout/CFooter/DesktopFooter.tsx, src/templates/page.tsx, src/types/resource.ts, src/types/section.ts, src/utils/getLink.ts
> Jira ticket: https://phildotus.atlassian.net/browse/MRTG-1135
=> Mrtg 1135: Revamp Home page

src/assets/css/hubspot-form.css, src/assets/css/index.css, src/components/common/Head/Head.tsx, src/components/sectionInColumn/basicSectionColumn/BasicSectionColumn.module.css, src/templates/demo-book/demoBook.template.tsx, src/templates/page.tsx
- separate out the Head component for reusability
- display the Head in the demo page
- fix the width display in the demo page
=> fix: add head in demo page

gatsby-browser.tsx, src/assets/css/index.css, src/components/LeftRigtContainer/LeftRightContainer.module.css, src/components/LeftRigtContainer/LeftRigthContainer.tsx, src/components/common/RichTextRenderer/RichTextRenderer.css, src/components/common/RichTextRenderer/RichTextRenderer.tsx, src/components/common/TrustpilotWidget/TrustPilotWidget.tsx, src/components/sectionInColumn/basicSectionColumn/BasicSectionColumn.module.css, src/components/sectionInColumn/basicSectionColumn/BasicSectionColumn.tsx, src/components/sectionInColumn/referncedSectionColumn/ReferenceSectionColumn.module.css, src/components/sectionInColumn/referncedSectionColumn/ReferencedSectionColumn.tsx, src/constants/global.constant.ts, src/contexts/PageContext.tsx, src/hooks/useIsLaptop.ts, src/templates/demo-book/demoBook.template.tsx, src/types/section.ts, src/utils/utils.ts
updates:
- make the right section of demo page fixed
- update css
=> fix: make right side of demo page fixed

src/components/icons/RightArrow.icon.tsx, src/components/sectionInColumn/basicSectionColumn/BasicSectionColumn.module.css, src/components/sectionInColumn/basicSectionColumn/BasicSectionColumn.tsx, src/constants/identifiers.ts
=> fix: add svg component icon

src/layouts/Layout/CHeader/header.module.css
ticket: [MRTG1173](https://phildotus.atlassian.net/browse/MRTG-1173)
- made the nav bar sticky
=> mrtg1173 : Make the Navbar sticky

src/components/LeftRigtContainer/LeftRightContainer.module.css, src/components/icons/RightArrow.icon.tsx, src/components/section/BasicSection/BasicSection.tsx, src/components/section/BasicSection/basicSection.module.css, src/components/sectionInColumn/basicSectionColumn/BasicSectionColumn.module.css, src/components/sectionInColumn/basicSectionColumn/BasicSectionColumn.tsx, src/components/sectionInColumn/referncedSectionColumn/ReferenceSectionColumn.module.css, src/constants/global.constant.ts, src/constants/identifiers.ts, src/layouts/Layout/CHeader/header.module.css, src/templates/page.tsx, src/types/section.ts
Update :
**Major**
- make the navbar sticky
- create Book demo banner
- add banner in the pharma, solution and home page
**Minor**
- fix CSS in the demo page with font and divider and icon
=> Develop to Main [May 7 2025]

src/components/LeftRigtContainer/LeftRightContainer.module.css, src/components/Resource/BookBannerFromResource/BookBannerFromResource.tsx, src/components/icons/RightArrow.icon.tsx, src/components/section/BasicSection/BasicSection.tsx, src/components/section/BasicSection/basicSection.module.css, src/components/sectionInColumn/basicSectionColumn/BasicSectionColumn.module.css, src/components/sectionInColumn/basicSectionColumn/BasicSectionColumn.tsx, src/components/sectionInColumn/referncedSectionColumn/ReferenceSectionColumn.module.css, src/constants/global.constant.ts, src/constants/identifiers.ts, src/layouts/Layout/CHeader/header.module.css, src/templates/page.tsx, src/templates/resources.tsx, src/types/resource.ts, src/types/section.ts
updates:
- create a new component to show the book banner of resources
=> Develop to main [may 9 2025]

src/components/common/Card/CardSection/CardSection.tsx, src/components/text-text-columnsv2/index.tsx, src/components/text-text-columnsv2/textandtext.module.css, src/constants/section.ts, src/layouts/Layout/CHeader/navigation.module.css, src/layouts/Layout/layout.module.css
- fixed header and subheader in the solution page
- fixed triangle color in the navbar
- added spacing in the underline
=> fix: header and navbar traingle issue

src/components/common/Card/CardSection/CardSection.tsx, src/components/text-text-columnsv2/index.tsx, src/components/text-text-columnsv2/textandtext.module.css, src/constants/section.ts, src/layouts/Layout/CHeader/navigation.module.css, src/layouts/Layout/layout.module.css
- fixed header and subheader in the solution page
- fixed triangle color in the navbar
- added spacing in the underline
=> Develop to main [May 15, 2025]

src/components/sectionInColumn/basicSectionColumn/BasicSectionColumn.module.css, src/components/sectionInColumn/basicSectionColumn/BasicSectionColumn.tsx, src/components/sectionInColumn/referncedSectionColumn/ReferenceSectionColumn.module.css, src/components/sectionInColumn/referncedSectionColumn/ReferencedSectionColumn.tsx
=> Develop to Main [may16 , 2025]

src/assets/css/index.css, src/components/common/Metric/Metric.tsx, src/components/common/Metric/metric.module.css, src/components/common/Resources/ResourceCard.tsx, src/layouts/Layout/CHeader/header.module.css, src/strategies/GenerateCaseStudyPages.ts, src/templates/case-study.tsx, src/templates/caseStudy.module.css, src/templates/resources.tsx, src/types/section.ts
Updates
- Case study modification
- metric component update
- css
=> Develop to main [may 22, 2025] 

src/components/common/Metric/metric.module.css, src/constants/section.ts, src/templates/case-study.tsx, src/templates/caseStudy.module.css
fix TOC scroll offset navbar in case study
update new book banner in the case study
=> fix: fixes in the case study page

src/components/common/Metric/metric.module.css, src/constants/section.ts, src/templates/case-study.tsx, src/templates/caseStudy.module.css
* fix: TOC scroll offset navbar
* fix: left right spacing by removing fluid
* fix: use new BookBanner in the casestudy
=> Develop to main [may 23, 2025] 

src/components/common/Card/CardSection/CardSection.tsx, src/components/common/Metric/metric.module.css, src/constants/page.ts, src/constants/routes.ts, src/templates/case-study.tsx
* fix: update the link in case study
* fix:add case study link in the solution page
=> Develop to Main [May 26, 2025]

src/components/common/KeyMetricOfCaseStudy/KeyMetricOfCaseStudy.module.css, src/components/common/KeyMetricOfCaseStudy/KeyMetricOfCaseStudy.tsx, src/templates/case-study.tsx, src/templates/caseStudy.module.css
=> fix: add the key metric of case study

src/components/career/CareerSection.tsx, src/components/career/careerSection.module.css
https://phildotus.atlassian.net/browse/MRTG-1210
=> MRTG-1210: make the career img sticky on top

src/assets/css/index.css, src/components/FeaturedInsights/FeaturedInsights.tsx, src/components/FeaturedInsights/featuredInsights.module.css, src/components/common/Asset/Asset.tsx, src/components/common/Container/ImageContainer.tsx, src/components/section/BasicSection/BasicSection.tsx, src/components/section/BasicSection/basicSection.module.css, src/components/section/ReferencedSection/referencedSection.module.css, src/components/section/ReferencedSection/referencedSectionTitle.module.css, src/templates/page.tsx, src/types/resource.ts
Revamp the company page  
* feat: update the company page structure
* fix: update the css in featureInsight
=> Develop to main [Jul 16, 2025]

src/layouts/Layout/CFooter/desktopFooter.module.css, src/templates/leadership.tsx
fix: use gatsby image in the leadership page
=> Develop to main [Jul 28, 2025]  

src/assets/css/index.css, src/components/ContactPageForm/ContactForm.tsx, src/components/ContactPageForm/contactForm.module.css, src/components/section/BasicSection/BasicSection.tsx, src/components/section/BasicSection/basicSection.module.css
- update the company banner image (make a slight bigger)
- remove the title in the contact form and display from the Hubspot itself
=> fix: update the company banner img and remove title in contact

src/assets/css/index.css, src/components/ContactPageForm/ContactForm.tsx, src/components/ContactPageForm/contactForm.module.css, src/components/section/BasicSection/BasicSection.tsx, src/components/section/BasicSection/basicSection.module.css
* fix: update the company banner img and remove title in contact
* fix: update the css in contact form
* fix: add the title in the contact form
=> Develop to main [Jul 29, 2025]

src/components/section/BasicSection/basicSection.module.css, src/layouts/Layout/CFooter/desktopFooter.module.css, src/layouts/Layout/CHeader/CDrawer.tsx, src/layouts/Layout/CHeader/drawer.module.css, src/layouts/Layout/CHeader/header.module.css, src/templates/leadership.tsx
=> fix: add the webp format for image optimization

src/components/section/BasicSection/basicSection.module.css, src/layouts/Layout/CFooter/desktopFooter.module.css, src/layouts/Layout/CHeader/CDrawer.tsx, src/layouts/Layout/CHeader/drawer.module.css, src/layouts/Layout/CHeader/header.module.css, src/templates/leadership.tsx
* fix: add the webp format for image optimization
* fix: adjust the company banner in responsive
* fix: stack the login button in mobile view
=> Develop to main [Jul 31, 2025] 

package.json, src/assets/css/hubspot-form.css, src/components/LeftRigtContainer/FloorContainer/FloorContainer.module.css, src/components/LeftRigtContainer/FloorContainer/FloorContainer.tsx, src/components/LeftRigtContainer/GridContainer/gridContainer.module.css, src/components/LeftRigtContainer/GridContainer/gridContainer.tsx, src/components/LeftRigtContainer/LeftRightContainer.module.css, src/components/LeftRigtContainer/LeftRigthContainer.tsx, src/components/brandOutcomeCard/BrandOutcomeCard.tsx, src/components/brandOutcomeCard/brandOutcomeCard.module.css, src/components/common/HubspotForm/HubspotFormV2.tsx, src/components/sectionInColumn/SectionInColumn.tsx, src/components/sectionInColumn/basicSectionColumn/BasicSectionColumn.module.css, src/components/sectionInColumn/basicSectionColumn/BasicSectionColumn.tsx, src/constants/identifiers.ts, src/layouts/Layout/Layout.tsx, src/templates/demo-book/demoBook.template.tsx, src/types/page.ts, src/types/section.ts
Parent Ticket: https://phildotus.atlassian.net/browse/MRTG-1226
Update:
- Revamp the demo page  with version 6 design
- Change the layout of the demo page in component level and contentful level
- Added new section i.e Text and Text Column with footer in contentful
- Update the css
- add new hubsport component of version 2 with checking the renderform exist or not before rendering it
Screenshot of the demo page:
screenshot of the new design in the input field:
=> Feat : New design for the Demo page (version 6)

src/components/LeaderProfileCard/LeaderProfileCard.module.css, src/components/LeaderProfileCard/LeaderProfileCard.tsx, src/components/career/careerSection.module.css, src/templates/leadership.module.css, src/templates/leadership.tsx
Parent ticket:https://phildotus.atlassian.net/browse/MRTG-1235
Child ticket: https://phildotus.atlassian.net/browse/MRTG-1237
1. New design for Learship page card:
2. Career page :
https://github.com/user-attachments/assets/95ab0e8f-d312-4ba4-82a3-89bf901ee73a
=> feat: create a leadership card

src/assets/css/index.css, src/components/Resource/AutoScrollCarousel/AutoScrollCarousel.module.css, src/components/common/PhilPeople/PhilPeople.module.css, src/components/common/PhilPeople/PhilPeople.tsx, src/components/section/BasicSection/BasicSection.tsx, src/components/section/BasicSection/basicSection.module.css, src/components/section/ReferencedSection/ReferencedSection.tsx, src/components/section/ReferencedSection/ReferencedSectionBody.tsx, src/components/section/ReferencedSection/RenderResource.tsx, src/components/section/ReferencedSection/referencedSection.module.css, src/constants/global.constant.ts, src/templates/page.tsx, src/types/section.ts
https://phildotus.atlassian.net/browse/MRTG-1235
=> Feat : Revamp Company page

package.json, src/assets/css/index.css, src/components/LeaderProfileCard/LeaderProfileCard.module.css, src/components/LeaderProfileCard/LeaderProfileCard.tsx, src/components/Resource/AutoScrollCarousel/AutoScrollCarousel.module.css, src/components/Resource/AutoScrollCarousel/AutoScrollCarousel.tsx, src/components/common/PhilPeople/PhilPeople.module.css, src/components/common/PhilPeople/PhilPeople.tsx, src/components/section/BasicSection/BasicSection.tsx, src/components/section/BasicSection/basicSection.module.css, src/components/section/ReferencedSection/ReferencedSection.tsx, src/components/section/ReferencedSection/ReferencedSectionBody.tsx, src/components/section/ReferencedSection/RenderResource.tsx, src/components/section/ReferencedSection/referencedSection.module.css, src/constants/global.constant.ts, src/constants/routes.ts, src/templates/leadership.tsx, src/templates/page.tsx, src/types/section.ts
* feat: create autoScrollCarousel
* fix: add the new field in the referencedsection
=> Develop to Main [Aug 28, 2025]

src/templates/blog.tsx
fix: use new YouTubeVideo component
=> Develop to Main [Oct 7, 2025]
